wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1669234898.912906
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.4
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 1
dataset:
  desc: null
  value:
  - ArteryObjAN1-17-nl.dat
epochs:
  desc: null
  value: 8000
learning_rate:
  desc: null
  value: 0.0001
number of trees:
  desc: null
  value: 1
optim:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    eps: 1e-08\n    lr: 0.0001\n    maximize: False\n    weight_decay: 0\n)"
