wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1668631285.277299
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 1
dataset:
  desc: null
  value:
  - test2.dat
epochs:
  desc: null
  value: 5000
learning_rate:
  desc: null
  value: 0.0001
number of trees:
  desc: null
  value: 1
