wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1669661844.788817
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 10
dataset:
  desc: null
  value:
  - tree0.dat
  - tree1.dat
  - tree10.dat
  - tree100.dat
  - tree101.dat
  - tree102.dat
  - tree103.dat
  - tree104.dat
  - tree105.dat
  - tree106.dat
  - tree107.dat
  - tree108.dat
  - tree109.dat
  - tree11.dat
  - tree110.dat
  - tree111.dat
  - tree112.dat
  - tree113.dat
  - tree114.dat
  - tree115.dat
  - tree116.dat
  - tree117.dat
  - tree118.dat
  - tree119.dat
  - tree12.dat
  - tree120.dat
  - tree121.dat
  - tree122.dat
  - tree123.dat
  - tree124.dat
  - tree125.dat
  - tree126.dat
  - tree127.dat
  - tree128.dat
  - tree129.dat
  - tree13.dat
  - tree130.dat
  - tree131.dat
  - tree132.dat
  - tree133.dat
  - tree134.dat
  - tree135.dat
  - tree136.dat
  - tree137.dat
  - tree138.dat
  - tree139.dat
  - tree14.dat
  - tree140.dat
  - tree141.dat
  - tree142.dat
  - tree143.dat
  - tree144.dat
  - tree145.dat
  - tree146.dat
  - tree147.dat
  - tree148.dat
  - tree149.dat
  - tree15.dat
  - tree150.dat
  - tree151.dat
  - tree152.dat
  - tree153.dat
  - tree154.dat
  - tree155.dat
  - tree156.dat
  - tree157.dat
  - tree158.dat
  - tree159.dat
  - tree16.dat
  - tree160.dat
  - tree161.dat
  - tree162.dat
  - tree163.dat
  - tree164.dat
  - tree165.dat
  - tree166.dat
  - tree167.dat
  - tree168.dat
  - tree169.dat
  - tree17.dat
  - tree170.dat
  - tree171.dat
  - tree172.dat
  - tree173.dat
  - tree174.dat
  - tree175.dat
  - tree176.dat
  - tree177.dat
  - tree178.dat
  - tree179.dat
  - tree18.dat
  - tree180.dat
  - tree181.dat
  - tree182.dat
  - tree183.dat
  - tree184.dat
  - tree185.dat
  - tree186.dat
  - tree187.dat
  - tree188.dat
epochs:
  desc: null
  value: 8000
learning_rate:
  desc: null
  value: 1.0e-05
number of trees:
  desc: null
  value: 100
optim:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    eps: 1e-08\n    lr: 1e-05\n    maximize: False\n    weight_decay: 0\n)"
